/**:
  ros__parameters:
    desired_freq: 10.0
    pad:
      num_of_buttons: 14
      num_of_axes: 14
      joy_topic: joy
      joy_timeout: 1.0
    plugins:
      - Movement
      - Charge
    
    Movement:
      type: robotnik_pad_plugins/Movement
      max_linear_speed: 1.0
      max_angular_speed: 1.5
      cmd_topic_vel: pad_teleop/cmd_vel
      config:
        button_deadman: 5
        axis_linear_x: 1
        axis_linear_y: 0
        axis_angular_z: 2
        button_speed_up: 3
        button_speed_down: 1
        button_kinematic_mode: 7
        use_accel_watchdog: true
        axis_watchdog: [6,7,8]
        watchdog_duration: 0.5

    Charge:
      type: robotnik_pad_plugins/Charge
      config:
        button_deadman: 5
        button_charge: 0
        button_uncharge: 2
      charge:
        action_name: charge
        robot_dock_frame: robot_base_docking_contact
        dock_frame: robotnik_marker_1
        dock_offset: 0.1
        retries: 3
      uncharge:
        action_name: uncharge
      action_timeout: 400.0
